// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwXaGzZplS4B7JrC1sQtD9TL0yjCV50SM',
    appId: '1:116885791416:web:0424cb39032483bbaf8a4d',
    messagingSenderId: '116885791416',
    projectId: 'projectmpsaya',
    authDomain: 'projectmpsaya.firebaseapp.com',
    storageBucket: 'projectmpsaya.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-ivm_bJVqxyq99VYMZL-HcD_f89naxhQ',
    appId: '1:116885791416:android:9be1ddfee8fe5d21af8a4d',
    messagingSenderId: '116885791416',
    projectId: 'projectmpsaya',
    storageBucket: 'projectmpsaya.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGJUopXQafH6x9fQ1IxhqqVPCXXWUT0IA',
    appId: '1:116885791416:ios:f0576bf9e92cce8daf8a4d',
    messagingSenderId: '116885791416',
    projectId: 'projectmpsaya',
    storageBucket: 'projectmpsaya.appspot.com',
    androidClientId: '116885791416-chdksveu5vi6ke4obu6figvsq1vi346k.apps.googleusercontent.com',
    iosClientId: '116885791416-0htsiu8adrh1ucf4b81c0j1s1b3ji1fr.apps.googleusercontent.com',
    iosBundleId: 'com.reza.projectsaya',
  );
}
